version: "3.8"
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./app:/app
    working_dir: /app

  web:
    container_name: web
    image: nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "18000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "13306:33060"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "18888:18888"
